if filereadable(expand("~/.vim/vimrc.bundles"))
	source ~/.vim/vimrc.bundles
endif
set runtimepath+=$GOROOT/misc/vim
syntax on
set number
set rnu
filetype plugin indent on
set hlsearch
set incsearch
set magic
set smarttab
set autoindent
set tabstop=4
set shiftwidth=4
map <Esc>[B <Down>]

let g:CSApprox_verbose_level = 0
map <F8> :NERDTreeToggle<cr>
map <F9> :TagbarToggle<cr>
" let g:NERDTreeDirArrows=0

"Set a nice Omnifunc - <CTRL>X <CTRL>O
set ofu=syntaxcomplete#Complete

 
" Make vim popup behave more like an IDE POPUP
set completeopt=longest,menuone

" Set default split positions
set splitright
set splitbelow

" Make enter finish the completion popup menu
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
nnoremap gp `[v`] 
set backspace=indent,eol,start
colorscheme desert256

" Move lines
nnoremap <C-Down> :m .+1<CR>==
nnoremap <C-Up> :m .-2<CR>==
inoremap <C-Down> <Esc>:m .+1<CR>==gi
inoremap <C-Up> <Esc>:m .-2<CR>==gi
vnoremap <C-Down> :m '>+1<CR>gv=gv
vnoremap <C-Up> :m '<-2<CR>gv=gv

set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"

set laststatus=2

if &t_Co == 256
    colorscheme Tomorrow-Night-Bright
endif

"Display whitespace characters
set listchars=tab:│\ ,trail:·
set list

"Fold Methods
set foldmethod=indent
set nofoldenable    "Stop from folding at load

if has('mouse')
  set mouse=a
endif

"Buffer Mappings
nmap <C-e> :b#<CR>
nmap <C-PageUp> :bnext<CR>
nmap <C-PageDown> :bprev<CR>

"Toggle Highlights
map <leader>q :noh<CR>

"Functions
function Opaq()
	set t_Co=256
	colorscheme Tomorrow-Night-Eighties
endfunction

function Transp()
	set t_Co=128
endfunction

"Smart Home (VimTip315)
function! SmartHome()
  let first_nonblank = match(getline('.'), '\S') + 1
  if first_nonblank == 0
    return col('.') + 1 >= col('$') ? '0' : '^'
  endif
  if col('.') == first_nonblank
    return '0'  " if at first nonblank, go to start line
  endif
  return &wrap && wincol() > 1 ? 'g^' : '^'
endfunction
noremap <expr> <silent> <Home> SmartHome()
imap <silent> <Home> <C-O><Home>

"Custom ignore for ctrlp
if exists("g:ctrl_user_command")
  unlet g:ctrlp_user_command
endif
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/vendor/*,*/\.git/*,*/bower_components/*,*/node_modules/*,*/dist/*

"signify: updte git markers when vim gains focus
let g:signify_update_on_focusgained = 0

"Tagbar config for Go
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }
