source ~/.antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting

antigen bundle <<EOBUNDLES
	git
	wd
	per-directory-history
	dirhistory
	tmux
	git-extras
	command-not-found
EOBUNDLES

antigen theme ys

antigen apply

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt inc_append_history
setopt HIST_IGNORE_DUPS


#Remove this hack later
if [[ -a "~/.zprofile" ]]
then
	source ~/.zprofile
else
	source ~/.profile
fi
