source ~/.zplug/init.zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/wd",   from:oh-my-zsh
zplug "plugins/per-directory-history",   from:oh-my-zsh
zplug "plugins/dirhistory",   from:oh-my-zsh
zplug "plugins/tmux",   from:oh-my-zsh
zplug "plugins/svn",   from:oh-my-zsh
zplug "plugins/git-extras",   from:oh-my-zsh
zplug "plugins/fancy-ctrl-z",   from:oh-my-zsh

zplug "themes/ys", from:oh-my-zsh, as:theme

zplug "kennethreitz/autoenv", defer:2

if ! zplug check; then
    zplug install
fi

zplug load

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt inc_append_history
setopt HIST_IGNORE_DUPS

source ~/.zshrc.alias
source ~/.profile

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
eval "$(pyenv init -)"
