abbr -a -- cp 'cp -v'
abbr -a -- evim 'sudo -E nvim'
abbr -a -- ga 'git add'
abbr -a -- gapa 'git add --patch'
abbr -a -- gb 'git branch'
abbr -a -- gba 'git branch -a'
abbr -a -- gc 'git commit -v'
abbr -a -- gc! 'git commit -v --amend'
abbr -a -- gcf 'git commit --fixup'
abbr -a -- gclean 'git clean -id'
abbr -a -- gco 'git checkout'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gd 'git diff'
abbr -a -- gdca 'git diff --cached'
abbr -a -- gf 'git fetch'
abbr -a -- gl 'git pull'
abbr -a -- glgg 'git log --graph'
abbr -a -- glog 'git log --oneline --decorate --graph'
abbr -a -- gp 'git push'
abbr -a -- gpu 'git push -u origin (current_branch)'
abbr -a -- gpuc 'git push -u origin (current_branch)'
abbr -a -- gr 'git rebase'
abbr -a -- gra 'git rebase --abort'
abbr -a -- grc 'git rebase --continue'
abbr -a -- grh 'git reset HEAD'
abbr -a -- grhh 'git reset --hard'
abbr -a -- grpe grep
abbr -a -- grt 'cd (git rev-parse --show-toplevel || echo .)'
abbr -a -- gst 'git status'
abbr -a -- gsta 'git stash'
abbr -a -- kick 'sudo systemctl'
abbr -a -- l 'ls -lah'
abbr -a -- ltrh 'ls -ltrh'
abbr -a -- mv 'mv -v'
abbr -a -- pax 'ps aux'
abbr -a -- paxgrep 'ps aux | grep'
abbr -a -- paxgrp 'ps aux | grep'
abbr -a -- pfax 'ps fax'
abbr -a -- rm 'rm -v'
abbr -a -- yt 'youtube-dl --no-mtime -ciw'
