abbr -a -U -- cp 'cp -v'
abbr -a -U -- evim 'sudo -E nvim'
abbr -a -U -- ga 'git add'
abbr -a -U -- gapa 'git add --patch'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gba 'git branch -a'
abbr -a -U -- gc 'git commit -v'
abbr -a -U -- gc! 'git commit -v --amend'
abbr -a -U -- gcf 'git commit --fixup'
abbr -a -U -- gclean 'git clean -id'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcp 'git cherry-pick'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gdca 'git diff --cached'
abbr -a -U -- gf 'git fetch'
abbr -a -U -- gl 'git pull'
abbr -a -U -- glgg 'git log --graph'
abbr -a -U -- glog 'git log --oneline --decorate --graph'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpu 'git push -u origin (current_branch)'
abbr -a -U -- gpuc 'git push -u origin (current_branch)'
abbr -a -U -- gr 'git rebase'
abbr -a -U -- gra 'git rebase --abort'
abbr -a -U -- grc 'git rebase --continue'
abbr -a -U -- grh 'git reset HEAD'
abbr -a -U -- grhh 'git reset --hard'
abbr -a -U -- grpe grep
abbr -a -U -- gst 'git status'
abbr -a -U -- gsta 'git stash'
abbr -a -U -- kick 'sudo systemctl'
abbr -a -U -- l 'ls -lah'
abbr -a -U -- ltrh 'ls -ltrh'
abbr -a -U -- mv 'mv -v'
abbr -a -U -- pax 'ps aux'
abbr -a -U -- paxgrep 'ps aux | grep'
abbr -a -U -- paxgrp 'ps aux | grep'
abbr -a -U -- pfax 'ps fax'
abbr -a -U -- rm 'rm -v'
abbr -a -U -- yt 'youtube-dl --no-mtime -ciw'
